before_script:
    - echo $PWD
    - id

stages:
    - build
    - build_production

compile:
    stage: build
    only:
        - staging
    tags:
        - aws
        - thaibulksms
    script:
        - rimraf out
        - yarn
        - yarn build
        - sudo -u www-data rsync -ar out/* /var/www/staging/thaibulksms-frontend-next
    cache:
        paths:
            - node_modules/
            - .next/

compile_production:
    stage: build_production
    only:
        - master
    tags:
        - aws
        - thaibulksms
    script:
        - rimraf out
        - yarn
        - yarn build
        - sudo -u www-data rsync -ar out/* /var/www/thaibulksms-frontend-next
    cache:
        paths:
            - node_modules/
            - .next/
